#!/bin/bash
#
rm -rf                PIGPIO
mkdir                 PIGPIO
#
cp command.c          PIGPIO
cp command.h          PIGPIO
cp pig2vcd.c          PIGPIO
cp pigpio.c           PIGPIO
cp pigpio.h           PIGPIO
cp pigpiod.c          PIGPIO
cp pigpiod_if.c       PIGPIO
cp pigpiod_if.h       PIGPIO
cp pigs.c             PIGPIO
#
cp pigpio.py          PIGPIO
cp setup.py           PIGPIO
#
cp README             PIGPIO
cp UNLICENCE          PIGPIO
#
cp x_pigpio.c         PIGPIO
cp x_pigpio.py        PIGPIO
cp x_pigpiod_if.c     PIGPIO
cp x_pigs             PIGPIO
cp x_pipe             PIGPIO
#
cp pig2vcd.1          PIGPIO
cp pigpiod.1          PIGPIO
cp pigs.1             PIGPIO
cp pigpio.3           PIGPIO
cp pigpiod_if.3       PIGPIO
#
cp Makefile           PIGPIO
cp MakeRemote         PIGPIO
#
zip -r pigpio-$1.zip  PIGPIO
tar cvf pigpio-$1.tar PIGPIO

